package com.example.android.noteit;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
//This java file contais the layout of the Credits page.
//No changes have been made in this file.This is the original file generated by Android Studio only the frontend have been modified(the XML file) to display the credits.

public class CreditsPage extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_credits_page);
    }
}
